/**
 * vite.config.ts — WashU SHPE
 *
 * DEPLOYMENT BASE PATH
 * --------------------
 * This app is deployed to two different roots:
 *
 *   GitHub Pages → https://gabbigabster.github.io/SHPE_Website/  (base "/SHPE_Website/")
 *   Netlify      → https://<site>.netlify.app/                   (base "/")
 *
 * `base` is therefore read from VITE_BASE_PATH instead of being hard-coded.
 * It defaults to "/SHPE_Website/" so an un-configured `npm run build` still
 * produces a correct GitHub Pages bundle (the historical behaviour).
 *
 * The same value is exposed as import.meta.env.BASE_URL and consumed by
 * App.tsx for React Router's basename and by lib/assets.ts for public assets,
 * so routing AND asset loading follow from this single setting.
 */

import { defineConfig, loadEnv, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

const DEFAULT_BASE = "/SHPE_Website/";

/**
 * GitHub Pages has no SPA rewrite rule: a hard refresh on /SHPE_Website/portal
 * makes it look for a file on disk, fail, and serve 404.html. This plugin emits
 * a 404.html that bounces the deep link back through index.html as a query
 * string, which the inline script in index.html then restores.
 *
 * `segmentCount` must equal the number of path segments in `base`, so the file
 * is generated rather than committed - a base of "/" needs 0, "/SHPE_Website/"
 * needs 1. A committed copy that lived outside public/ is how deep links
 * silently broke before: Vite never copied it into dist at all.
 *
 * Technique by Rafael Pedicini: https://github.com/rafgraph/spa-github-pages
 */
function githubPages404(base: string): Plugin {
  const segmentCount = base.split("/").filter(Boolean).length;

  return {
    name: "washu-shpe:github-pages-404",
    apply: "build",
    generateBundle() {
      this.emitFile({
        type: "asset",
        fileName: "404.html",
        source: [
          "<!doctype html>",
          '<html lang="en">',
          "  <head>",
          '    <meta charset="UTF-8" />',
          "    <title>Redirecting</title>",
          "    <script>",
          "      // Generated by vite.config.ts - do not edit by hand.",
          "      var segmentCount = " + segmentCount + ";",
          "      var l = window.location;",
          "      l.replace(",
          '        l.protocol + "//" + l.hostname + (l.port ? ":" + l.port : "") +',
          '        l.pathname.split("/").slice(0, 1 + segmentCount).join("/") +',
          '        "/?p=/" +',
          '        l.pathname.slice(1).split("/").slice(segmentCount).join("/").replace(/&/g, "~and~") +',
          '        (l.search ? "&q=" + l.search.slice(1).replace(/&/g, "~and~") : "") +',
          "        l.hash",
          "      );",
          "    <" + "/script>",
          "  </head>",
          "  <body>Redirecting...</body>",
          "</html>",
          "",
        ].join("\n"),
      });
    },
  };
}


/** Normalise to a leading+trailing slash form, which is what Vite expects. */
function normaliseBase(raw: string | undefined): string {
  if (!raw) return DEFAULT_BASE;
  const trimmed = raw.trim();
  if (trimmed === "" || trimmed === "/") return "/";
  return `/${trimmed.replace(/^\/+|\/+$/g, "")}/`;
}

export default defineConfig(({ mode }) => {
  // loadEnv also picks the value up from .env files, not just process.env,
  // so `VITE_BASE_PATH=/` in .env.local works for local Netlify-style dev.
  const env = loadEnv(mode, process.cwd(), "");
  const base = normaliseBase(env.VITE_BASE_PATH ?? process.env.VITE_BASE_PATH);

  return {
    plugins: [react(), githubPages404(base)],

    base,

    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./src"),
      },
    },

    build: {
      target: "es2020",
      sourcemap: false,
      chunkSizeWarningLimit: 700,

      rollupOptions: {
        // Explicit entry point → guarantees Vite uses index.html/main.tsx
        input: path.resolve(__dirname, "index.html"),

        output: {
          /**
           * Split vendor code so the browser can cache framework code
           * independently of app code. Supabase and React Query are only
           * pulled in by portal/admin chunks, so they get their own bundles
           * and are never shipped to a public-site-only visitor.
           */
          manualChunks(id) {
            if (
              id.includes("node_modules/react/") ||
              id.includes("node_modules/react-dom/") ||
              id.includes("node_modules/react-router/") ||
              id.includes("node_modules/react-router-dom/") ||
              id.includes("node_modules/scheduler/")
            ) {
              return "vendor-react";
            }
            if (id.includes("node_modules/lucide-react/")) {
              return "vendor-icons";
            }
            if (id.includes("node_modules/@supabase/")) {
              return "vendor-supabase";
            }
            if (id.includes("node_modules/@tanstack/")) {
              return "vendor-query";
            }
            if (
              id.includes("node_modules/react-hook-form/") ||
              id.includes("node_modules/@hookform/") ||
              id.includes("node_modules/zod/")
            ) {
              return "vendor-forms";
            }
          },

          chunkFileNames: "assets/js/[name]-[hash].js",
          entryFileNames: "assets/js/[name]-[hash].js",
          assetFileNames: "assets/[ext]/[name]-[hash].[ext]",
        },
      },
    },

    // Inline only tiny assets (< 4 kB); keep images as separate files
    // so the browser can lazy-load and cache them individually.
    assetsInlineLimit: 4096,

    server: {
      port: 5173,
    },
  };
});
